services:
  airflow:
    build:
      context: .
      dockerfile: airflow/Dockerfile
    command: standalone
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/project/airflow/dags
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "true"
      PYTHONPATH: /opt/airflow/project
    volumes:
      - ./:/opt/airflow/project
      - airflow-db:/opt/airflow
volumes:
  airflow-db:
